// <auto-generated />
using System;
using Lisans.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lisans.Data.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20200615204515_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Lisans.Data.Models.DistrictModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ProviceId");

                    b.HasKey("Id");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Lisans.Data.Models.LisansModel", b =>
                {
                    b.Property<int>("LisansId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("District");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("HardwareId")
                        .IsRequired();

                    b.Property<DateTime>("LastOnlineDate");

                    b.Property<string>("OfflineProductKey");

                    b.Property<string>("OnlineProductKey");

                    b.Property<int>("Province");

                    b.Property<string>("SchoolCode")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("SchoolName")
                        .IsRequired();

                    b.Property<short>("Status");

                    b.HasKey("LisansId");

                    b.ToTable("Lisans");
                });

            modelBuilder.Entity("Lisans.Data.Models.ProvinceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });
#pragma warning restore 612, 618
        }
    }
}
